# See https://hub.docker.com/_/node for available tags
FROM mcr.microsoft.com/devcontainers/node:20-bookworm

# Install pnpm
RUN npm install -g pnpm

# Install additional tools if needed
# RUN apt-get update && apt-get install -y ...

WORKDIR /workspace
